typedef enum {
    UNKNOWN_OP_CODE=22,
    INVALID_SYNTAX=23,
    SEMANTIC_ERROR=52,
    WRONG_OPERAND_TYPE=53,
    UNDEFINED_VARIABLE_ACCESS=54,
    NONEXISTING_MEMORY_FRAME=55,
    MISSING_STACK_VALUE=56,
    INVALID_OPERAND_VALUE=57,
    INVALID_STRING_OPERATION=58,
} int_ret_code;