#ifndef __RET_CODES_H__
#define __RET_CODES_H__

typedef enum {
    PROGRAM_OK=0,
    INVALID_ARG=10,
    INPUT_FILE_OPEN_ERR=11,
    UNKNOWN_OP_CODE=22,
    INVALID_SYNTAX=23,
    SEMANTIC_ERROR=52,
    WRONG_OPERAND_TYPE=53,
    UNDEFINED_VARIABLE_ACCESS=54,
    NONEXISTING_MEMORY_FRAME=55,
    MISSING_STACK_VALUE=56,
    INVALID_OPERAND_VALUE=57,
    INVALID_STRING_OPERATION=58,
    INTERNAL_ERROR=99
} int_ret_code;
#endif